### ISSUE TITLE
Reverse only works from end of video when first played?

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-video#7] opened 2014-07-22 21:21 UTC
<a href="https://github.com/processing-bugs"><img src="https://avatars.githubusercontent.com/u/3503183?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [processing-bugs](https://github.com/processing-bugs)**
_Sunday Feb 10, 2013 at 17:43 GMT_
_Originally opened as https://github.com/processing/processing/issues/1505_

---

_Original author: daniel.s...@gmail.com (December 11, 2012 20:49:58)_

Using the example &quot;Reverse&quot; I adjusted it to set the movie to play in reverse when the mouse is pressed.  This didn't work, however, I know this movie will play in reverse since the original example works.

I tried pausing, stopping, etc. but didn't have any luck.

See attached.

_Original issue: http://code.google.com/p/processing/issues/detail?id=1467_

**Comment by codeanticode** [comment] 2019-08-25 13:50
Probably duplicate of #64

**Closed by codeanticode** 2019-08-25 13:50 UTC
Labels: bug, duplicate, imported, video
