### ISSUE TITLE
Mac OS Catalina...

### ISSUE THREAD

**Issue by NoBodyButMe** [processing/processing-video#147] opened 2020-03-09 21:22 UTC
Video library is not working. Just grey screen and crash.

**Comment by christo** [comment] 2020-06-23 04:54
I've been trying this on Catalina and I haven't had your problem. Maybe you could post some code so people could try it out and look into it?

**Comment by christo** [comment] 2020-06-23 04:55
Actually maybe this is a duplicate of #134  ?

**Comment by benfry** [comment] 2020-10-08 11:05
Closing as duplicate of #134.

**Closed by benfry** 2020-10-08 11:05 UTC
