### ISSUE TITLE
excessive permissions in Catalina with version 2 beta 4

### ISSUE THREAD

**Issue by nosarious** [processing/processing-video#157] opened 2020-07-28 17:50 UTC
I am running Processing 3.5.4 on a MacBook Pro 13 inch (2019)  with Catalina 10.15.6

I have downloaded video library version 2, beta 4.

I am having problems with running the Getting Started program. It keeps saying this is from an unverified developer and not working properly. The Video folder, which had been copied into the Libraries folder, is showing up in the 'contributed libraries' when I access examples.

I have gone through the process of giving permissions whenever MacOSX brought up the dialog about the unverified developer, using system preferences, but it did so for EVERY .dylib file in the folder.

The second time I run the program, after going through all of these permissions, it will ask if it is okay to run them. for EVERY library. This seems rather tedious. Did I do something wrong? Is it not a simple 'move this folder into the Processing/Libraries folder?

Is there something I missed?

**Comment by nosarious** [comment] 2020-07-28 18:17
solved using this process:

https://github.com/processing/processing-video/issues/134#issuecomment-550000519

> 
> v2 library works on catalina, thank you @codeanticode
> 
> How to install
> 
> replace ~/Documents/processing/libraries/video with "video" folder from https://github.com/processing/processing-video/releases/tag/r6-v2.0-beta4
> open console, cd to ~/Documents/processing/libraries/video/library/macosx
> $ xattr -p com.apple.quarantine libavcodec.58.35.100.dylib
> it will return string like this:
> 0081;5dc1bfaa;Chrome;78F18F7D-3F71-4E55-8D58-BAB946AB4707
> 
> replace 0081 with 00c1 and copy string
> 
> then replace STRING in the following command with your string
> $ xattr -w com.apple.quarantine "STRING" *.dylib
> it will fix all libraries in this folder
> 
> then cd to gstreamer-1.0/ and run command again

`cd ~/Documents/processing/libraries/video/library/macosx `
`xattr -p com.apple.quarantine libavcodec.58.35.100.dylib`

(important string)

`xattr -w com.apple.quarantine "STRING" *.dylib` (if you have copied/pasted this command  then copy/paste the important string/ use the left arrow to go back and delete STRING. Paste and change 008* to 00c1 

`cd gstreamer-1.0` and do the same command as you just did (use up-arrow to save retyping it, press enter)

gstreamer-1.0 is a folder in the machos folder. for beta 4 it was 0083 on my machine that needed to be changed, not 0081 as mentioned.

**Comment by scottmetoyer** [comment] 2020-08-14 19:10
I followed these steps, but the GettingStartedCapture example sketched fails with the error message "Could not run the sketch (Target VM failed to initialize)." 

Any ideas?

**Comment by nosarious** [comment] 2020-08-21 03:18
I'm not sure. you would need to provide more information. What system are you running on, what version of processing, etc.

**Comment by benfry** [comment] 2020-10-08 11:04
Closing as duplicate of #134.

**Closed by benfry** 2020-10-08 11:04 UTC
