### ISSUE TITLE
USB Capture Device in Camera.list but doesn't respond , works with camera test software

### ISSUE THREAD

**Issue by jeffmarc10** [processing/processing-video#81] opened 2017-09-17 05:38 UTC
So I have tested several USB 2.0 Capture Devices, they are all recognized by Device Manager in Video devices.
They all work with googled video capture utilities, such as Debut, Webcamsave, etc.
THey all show up in the Camera.list
But none will work with Processing capture to capture a video or snapshot.
The forums in Processing mention this is a known problem and may be worked on in 2015.
But its 2017 and it still doesn't work.
How do we get this done?

**Comment by acdean** [comment] 2017-09-17 18:22
duplicate of #73

**Closed** 2019-04-03 16:19 UTC
Labels: duplicate
