### ISSUE TITLE
'A library used by this sketch is not installed properly' with video on Windows

### ISSUE THREAD

**Issue by benfry** [processing/processing-video#10] opened 2014-07-25 22:46 UTC
https://github.com/processing/processing/issues/2472

**Comment by codeanticode** [comment] 2019-08-25 13:56
After going through the original thread, seems that that this error was caused by non-ASCII characters in the path to the library. So, a duplicate of #6, which is probably solved by the update to GStreamer 1.x

**Closed by codeanticode** 2019-08-25 13:56 UTC
Labels: duplicate
