### ISSUE TITLE
Processing Video on Mac

### ISSUE THREAD

**Issue by KazimWalji** [processing/processing-video#162] opened 2020-05-11 03:50 UTC
WHen i try to caputure and show video in processing nothing works. Just gray screen. I deleted and redownloaded processing yet no luck. I cant display video, and its SO FRUSTRATING! ANy help? I didnt write my code, just copy and pasted the simple program for displaying webcam video from processing.org

**Comment by benfry** [comment] 2020-09-23 17:42
Duplicate of https://github.com/processing/processing-video/issues/134

**Closed by benfry** 2020-09-23 17:42 UTC
