### ISSUE TITLE
Mac video library bug exists

### ISSUE THREAD

**Issue by IsraelSuen** [processing/processing-video#159] opened 2020-08-01 18:01 UTC
2020-08-02 01:57:28.414 java[4930:240123] -[__NSArray0 addObjectsFromArray:]: unrecognized selector sent to instance 0x7fff90d7c460
2020-08-02 01:57:28.414 java[4930:240123] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSArray0 addObjectsFromArray:]: unrecognized selector sent to instance 0x7fff90d7c460'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff3958ab57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff723d15bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff39609be7 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff394ef3bb ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff394eed98 _CF_forwarding_prep_0 + 120
	5   libgstapplemedia.so                 0x000000012feb72bc libgstapplemedia.so + 58044
	6   jna3200880202271133509.tmp          0x000000012eb02134 ffi_call_unix64 + 76
	7   ???                                 0x000070000a4a4278 0x0 + 123145474949752
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Could not run the sketch (Target VM failed to initialize).
For more information, read revisions.txt and Help → Troubleshooting.

**Comment by sam959** [comment] 2020-09-04 05:35
I have the same issue on macOS Catalina 10.15.6 (19G2021).
Cannot use Capture object in any way.

**Comment by christo** [comment] 2020-09-08 04:34
What *is* this bug? @sam959 clearly you are reporting an issue triggered when attempting to use a Capture object - how did you get to the conclusion that it was the same issue that @IsraelSuen is reporting? I can't see anything in the description of this issue about what the user was trying to do when a crash occurred. The title is "Mac video library bug exists". That's maximally vague. Does anyone know what problem is being described? I'd love to help.

**Comment by sam959** [comment] 2020-09-08 10:05
@christo Everybody would like to help with this issues,
It is discussed here too: 
https://discourse.processing.org/t/did-macos-catalina-or-something-break-the-video-library/14699
Might be the same therefore the link I provided in the first comment could be handy. Otherwise we'll wait for more info about the issue from @IsraelSuen!
Cheers 👍

**Comment by christo** [comment] 2020-09-08 12:20
Hey @sam959, thanks for your reply. Yes I've heard about the problems people are having with `Capture` on MacOS Catalina. That bug seems to be tracked many times (although I can't be sure they are all identical) and a brief search shows at least these: #134 #144 #142 #160

**Comment by benfry** [comment] 2020-09-23 18:02
Duplicate of #134.

**Closed by benfry** 2020-09-23 18:02 UTC
