### ISSUE TITLE
Playing Video Does Not Work On MacOS 11

### ISSUE THREAD

**Issue by highjeans** [processing/processing-video#173] opened 2021-01-17 22:51 UTC
I downloaded processing from processing.org, and I copied the libraries to my project, but the project won't play videos at all. My project is at [https://github.com/highjeans/VideoFilter](https://github.com/highjeans/VIdeoFilter). I tried a lot of changes to the lib folder but still nothing will work. Can you please help? Even stranger, the Processing app plays the video successfully but showing the webcam does not work, while in my project showing a webcam works but playing a video does not work. 

Things I tried:

Action -> Result

Copied all .dylib files from macosx folder to lib folder -> video does not work
Copied gluegen-rt-natives-macosx-universal.jar and jogl-all-natives-macosx-universal.jar to lib -> video does not work
Removed all .dll files from lib -> video still did not work

**Comment by benfry** [comment] 2021-01-17 23:27
Duplicate of https://github.com/processing/processing-video/issues/134

**Closed by benfry** 2021-01-17 23:27 UTC
